---
- name: CIS 1.4.2 - Ensure access to bootloader config is configured
  hosts: all
  become: true

  tasks:

    - name: Set ownership and permissions on GRUB environment file
      ansible.builtin.file:
        path: /boot/grub2/grubenv
        owner: root
        group: root
        mode: '0600'
